=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Repaso/repasolm2.dtd
<!ELEMENT cancion (titulo, (compositores*, productores*, sello?, artista+)*)>
<!ATTLIST cancion
          anio CDATA #REQUIRED
          duracion CDATA #IMPLIED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT compositores (compositor?)>
<!ELEMENT compositor ((nombres, apellidos?) | (apellidos?, nombres))>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT productores (productor?)>
<!ELEMENT productor (nombres, apellidos)>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT artista (#PCDATA)>

=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Repaso/repasolm1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE cancion SYSTEM "repasolm2.dtd">-->
<!--<?xml-stylesheet type="text/xsl" href="file:repasolm3.xsl"?>-->
<cancion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repasolm3.xsd" duracion="4:47" anio="2008">
  <titulo>Give it 2 me</titulo>
  <compositores>
    <compositor>
      <nombres>Pharrell</nombres>
      <apellidos>Williams</apellidos>
    </compositor>
  </compositores>
  <productores>
    <productor>
      <nombres>Pharrell</nombres>
      <apellidos>Williams</apellidos>
    </productor>
  </productores>
  <sello>Warner Music Group</sello>
  <artista>Madonna</artista>
</cancion>
