=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Repaso/repasolm4.dtd
<!ELEMENT personajeHistorico (nombre, imagen, datosPersonales, enlace)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT datosPersonales (nacimiento, fallecimiento?, ocupaciones, descripcion)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT fallecimiento (#PCDATA)>
<!ELEMENT ocupaciones (ocupacion+)>
<!ELEMENT ocupacion (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT enlace (#PCDATA)>

=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Repaso/PersonajeH3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE personajeHistorico SYSTEM "repasolm4.dtd">-->
<personajeHistorico xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repasolm4.xsd">
  <nombre>Linus Torvalds</nombre>
  <imagen>linus.jpg</imagen>
  <datosPersonales>
    <nacimiento>28 de diciembre de 1969 (edad 52 años), Helsinki, Finlandia</nacimiento>

    <ocupaciones>
     <ocupacion>Ingeniero de software</ocupacion>
    </ocupaciones>
    <descripcion>Linus Benedict Torvalds es un ingeniero de software finlandés-estadounidense, ​ conocido por iniciar y mantener el desarrollo del kernel Linux, basándose en el sistema operativo libre Minix creado por Andrew S. Tanenbaum y en algunas herramientas, varias utilidades y los compiladores desarrollados por el proyecto GNU. </descripcion>
  </datosPersonales>
  <enlace>https://es.wikipedia.org/wiki/Linus_Torvalds</enlace>
</personajeHistorico>

=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Repaso/PersonajeH2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE personajeHistorico SYSTEM "repasolm4.dtd">-->
<personajeHistorico xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repasolm4.xsd">
  <nombre>Douglas Engelbart</nombre>
  <imagen>Douglas.jfif</imagen>
  <datosPersonales>
    <nacimiento>30 de enero de 1925, Portland, Oregón, Estados Unidos</nacimiento>
    <fallecimiento>2 de julio de 2013, Atherton, California, Estados Unidos</fallecimiento>
    <ocupaciones>
     <ocupacion>informático</ocupacion>
     <ocupacion>inventor</ocupacion>
    </ocupaciones>
    <descripcion>Douglas Carl Engelbart ​ fue un inventor estadounidense, descendiente de noruegos. Es conocido por inventar el ratón, ​ y fue un pionero de la interacción humana con las computadoras, incluyendo el hipertexto y las computadoras en red.​</descripcion>

  </datosPersonales>
  <enlace>https://es.wikipedia.org/wiki/Douglas_Engelbart</enlace>
</personajeHistorico>

=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Repaso/PersonajeH1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE personajeHistorico SYSTEM "repasolm4.dtd">-->
<personajeHistorico xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="repasolm4.xsd">
  <nombre>Ada Lovelace</nombre>
  <imagen>AdaLovelace.jpg</imagen>
  <datosPersonales>
    <nacimiento>10 de diciembre de 1815, Londres, Reino Unido</nacimiento>
    <fallecimiento>27 de noviembre de 1852, Marylebone, Londres, Reino Unido</fallecimiento>
    <ocupaciones>
     <ocupacion>Matemática</ocupacion>
     <ocupacion>Programadora</ocupacion>
     <ocupacion>Informatica teorica</ocupacion>
     <ocupacion>Poeta</ocupacion>
     <ocupacion>Ingeniera</ocupacion>
     <ocupacion>Traductora</ocupacion>
     <ocupacion>Escritora</ocupacion>
    </ocupaciones>
    <descripcion>Augusta Ada King, condesa de Lovelace, registrada al nacer como Augusta Ada Byron y conocida habitualmente como Ada Lovelace, fue una matemática y escritora británica, célebre sobre todo por su trabajo acerca de la computadora mecánica de uso general de Charles Babbage, la denominada máquina analítica.</descripcion>

  </datosPersonales>
  <enlace>https://es.wikipedia.org/wiki/Ada_Lovelace</enlace>
</personajeHistorico>
