<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listacompras
[
  <!ELEMENT listacompras (venta+)>
  <!ELEMENT venta (ventainmediata | ventaacredito)>
  <!ELEMENT ventaacredito (fechafinpago?, cantidad)>
  <!ELEMENT ventainmediata (cantidad, divisa)>
  <!ELEMENT cantidad (#PCDATA)>
  <!ELEMENT divisa (#PCDATA)>
  <!ELEMENT fechafinpago (#PCDATA)>
]>
<listacompras>
    <venta>
        <ventaacredito>
            <fechafinpago>22-10-2021</fechafinpago>
            <cantidad>21000</cantidad>
        </ventaacredito>
    </venta>
    <venta>
        <ventainmediata>
            <cantidad>1800</cantidad>
            <divisa>euros</divisa>
        </ventainmediata>
    </venta>
    <venta>
        <ventaacredito>
            <cantidad>21000</cantidad>
        </ventaacredito>
    </venta>
</listacompras>
