=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Tema 4 - XML/Tarea 08 - Casos Finales/casoFinal03.dtd
<!ELEMENT pedidos (pedido+)>
<!ELEMENT pedido ((empresa|cliente), productos+, fecha, factura?)>
<!ELEMENT factura (emisor, total+, fecha_fact)>
<!ELEMENT cliente (MOTE)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT productos (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT emisor (#PCDATA)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT fecha_fact (#PCDATA)>
<!ELEMENT MOTE (#PCDATA)>
<!ATTLIST cliente NIF CDATA #REQUIRED>
<!ATTLIST factura numfactura ID #REQUIRED>
<!ATTLIST factura cliente_factura CDATA #IMPLIED>

=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Tema 4 - XML/Tarea 08 - Casos Finales/casoFinal03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE pedidos SYSTEM "casoFinal03.dtd"> -->
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="casoFinal03.xsd">

  <pedido>
   <empresa>2113</empresa>
   <productos>Peras</productos>
   <fecha>7/10/2019</fecha>
   <factura numfactura="A1" cliente_factura="asdr">
      <emisor>Noelia</emisor>
      <total>192</total>
      <fecha_fact>7/10/2019</fecha_fact>
   </factura>
  </pedido>
  
  <pedido>
    <cliente NIF="253">
      <MOTE>Jaimito</MOTE>
    </cliente>
    <productos>Manzanas</productos>
    <fecha>9/8/2019</fecha>
    <factura numfactura="A2" cliente_factura="tges">
      <emisor>Pepa</emisor>
      <total>322</total>
      <fecha_fact>9/8/2019</fecha_fact>
    </factura>
  </pedido>
  
</pedidos>
