=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Lenguaje/Simulacro/Ejercicio02-Simulacro.dtd
<!ELEMENT empleados (persona+)>
<!ELEMENT persona (nombre, nacimiento?, direccion+)>
<!ATTLIST persona genero (hombre | mujer | noBinario) #REQUIRED>
<!ELEMENT nacimiento (dia | mes | año)*>
<!ELEMENT direccion (calle, provincia)>
<!ATTLIST direccion cp CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Lenguaje/Simulacro/pruebaFinal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<empleados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio03-Simulacro.xsd">-->
<!DOCTYPE empleados SYSTEM "Ejercicio02-Simulacro.dtd">
<empleados>
<!--PERSONA 1 -->
  <persona genero="hombre">
    <nombre>Mario Rodriguez</nombre>
    <direccion cp="28902">
      <calle>c/ graminias</calle>
      <provincia>Madrid</provincia>
    </direccion>
    <direccion cp="28903">
      <calle>c/ gardenias</calle>
      <provincia>Pamplona</provincia>
    </direccion>
  </persona>
  <!--PERSONA 2 -->
  <persona genero="noBinario">
    <nombre>Danielle Marquez</nombre>
    <nacimiento>
      <mes>septiembre</mes>
      <dia>01</dia>
      <año>1990</año>
    </nacimiento>
    <direccion cp="28731">
      <calle>c/ acacia</calle>
      <provincia>Madrid</provincia>
    </direccion>
  </persona>
  <!--PERSONA 3 -->
  <persona genero="hombre">
    <nombre>Javier Gutierrez</nombre>
    <nacimiento>
      <año>1989</año>
      <mes>diciembre</mes>
      <dia>11</dia>
    </nacimiento>
    <direccion cp="28933">
      <calle>c/ huerta</calle>
      <provincia>Madrid</provincia>
    </direccion>
    <direccion cp="45005">
      <calle>c/ asturias</calle>
      <provincia>Toledo</provincia>
    </direccion>
  </persona>
</empleados>

=== cesardro/DAW/DAW1/Lenguaje de Marcas/Trimestre 2/Lenguaje/Simulacro/Ejercicio01-Simulacro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados SYSTEM "Ejercicio02-Simulacro.dtd">
<empleados>
  <persona genero="hombre" >
    <nombre>Juan Jiménez</nombre>
    <nacimiento>
      <dia>09</dia>
      <mes>febrero</mes>
      <año>1992</año>
    </nacimiento>
    <direccion cp="28001">
      <calle>c/ Amatista</calle>
      <provincia>Madrid</provincia>
    </direccion>
  </persona>
  <persona genero="mujer">
    <nombre>María Fernández</nombre>
    <nacimiento>
      <dia>01</dia>
      <mes>junio</mes>
      <año>1975</año>
    </nacimiento>
    <direccion cp="28731">
      <calle>c/ Acacia</calle>
      <provincia>Madrid</provincia>
    </direccion>
  </persona>
  <persona genero="noBinario">
    <nombre>Logan Rio</nombre>
    <direccion cp="28003">
      <calle>c/ Huerta</calle>
      <provincia>Madrid</provincia>
    </direccion>
    <direccion cp="45006">
      <calle>c/ Asturias</calle>
      <provincia>Toledo</provincia>
    </direccion>
  </persona>
</empleados>
