<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arboles[
 <!ELEMENT arboles (arbol*)>
  <!ELEMENT arbol (nombre_comun, altura, forma_y_estructura, color_en_primavera, color_en_otoño?,resistencia_a_las_heladas)>
  <!ATTLIST arbol
            nombre_tecnico CDATA #IMPLIED
            vegetacion (caducifolio | perenne) #REQUIRED>
  <!ATTLIST altura
            minima CDATA #IMPLIED
            maxima CDATA #IMPLIED
            entorno CDATA #IMPLIED>
  <!ATTLIST resistencia_a_las_heladas temperatura CDATA #REQUIRED>
  <!ELEMENT nombre_comun (#PCDATA)>
  <!ELEMENT altura (#PCDATA)>
  <!ELEMENT forma_y_estructura (#PCDATA)>
  <!ELEMENT color_en_primavera (#PCDATA)>
  <!ELEMENT color_en_otoño (#PCDATA)>
  <!ELEMENT resistencia_a_las_heladas (#PCDATA)>
]>
<arboles>
  <arbol nombre_tecnico="Acer monspessulanum" vegetacion="caducifolio">
    <nombre_comun>Arce de Montpellier, Arce menor</nombre_comun>
    <altura minima="6" maxima="10"></altura>
    <forma_y_estructura>Copa esférica. Tronco principal recto con bifucrcaciones. Ramaje colgante</forma_y_estructura>
    <color_en_primavera>Haz verde rbillante, envés verde blanqucino</color_en_primavera>
    <resistencia_a_las_heladas temperatura="hasta -15*C">Heladas fuertes</resistencia_a_las_heladas>
  </arbol>
  <arbol nombre_tecnico="Olea europea" vegetacion="perenne">
    <nombre_comun>Olivo</nombre_comun>
    <altura minima="8" maxima="15"></altura>
    <forma_y_estructura>Copa irregular. Tronco principal irregular con bifurcaciones. Ramaje tortuoso</forma_y_estructura>
    <color_en_primavera>Haz verde oscuro, envés verde plateado</color_en_primavera>
    <resistencia_a_las_heladas temperatura="hasta -10*C">Heladas medias</resistencia_a_las_heladas>
  </arbol>
  <arbol nombre_tecnico="Platanus orientalis" vegetacion="caducifolio">
    <nombre_comun>Plátano</nombre_comun>
    <altura minima="20" maxima="25"></altura>
    <forma_y_estructura>Copa ovoidal. Tronco principal recto. Ramaje expandido</forma_y_estructura>
    <color_en_primavera>Haz verde medio, envés verde claro</color_en_primavera>
    <color_en_otoño>Ocre</color_en_otoño>
    <resistencia_a_las_heladas temperatura="hasta -20*C">Heladas fuertes</resistencia_a_las_heladas>
  </arbol>
  <arbol nombre_tecnico="Quercus ilex" vegetacion="perenne">
    <nombre_comun>Plátano</nombre_comun>
    <altura entorno="25"></altura>
    <forma_y_estructura>Copa esférica o elíptica irregular. Tronco principal recto. Ramaje tortuoso</forma_y_estructura>
    <color_en_primavera>Plateado en hojas jóvenes. En hojas antiguas, haz verde oscuro, envés plateado</color_en_primavera>
    <resistencia_a_las_heladas temperatura="hasta -15*C">Heladas fuertes</resistencia_a_las_heladas>
  </arbol>
</arboles>
